project:
  type: website
  output-dir: docs

website:
  title: "How to transition from a data analyst role to data scientist."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



