---
title: "Transitioning into a data scientist role as a data analyst and where to pick up new skills"
author: "Abdul Safdar"
date: "2025-01-14"
categories: [jobs]
---
# Transitioning Into a Data Scientist Role as a Data Analyst Where To Learn These Skills

# Introduction

Data science has been growing at a rapid rate. According to a report from the U.S. Bureau of Labor Statistics which can be found [here](https://www.bls.gov/ooh/math/data-scientists.htm), employment of data scientists from 2023 to 2033 is expected to grow by 36% with close to 20000 new jobs projected to be required each year. The median pay is also around $108000 according to this report making data science a viable choice. As a data analyst, you may be wondering how the role of a data scientist differs from a data analyst and why you should care? The difference according to [this blog](https://www.datacamp.com/blog/data-analyst-vs-data-scientist-a-comparative-guide) is that a data scientists role are more hands on in terms of building predictive modeling tools, whereas a data analyst is more concerned with generating actionable insights from data. If these reasons are compelling enough for you to consider making the transition, keep reading on! This blog post will outline where you can learn the required skills to become a proficient data scientist. 

# Prerequisite Skills Required
If you are working as a data analyst, I will assume that you know how to use a computer and Microsoft Office. You likely already have experience with relational databases, such as SQL as well as perhaps using dashboard preparation tools such as Power BI or Tableau. 

Before we go any further, I think it is important to share a list of prerequisite knowledge that I think will make your life easier if you have a good undestanding of. 

The first skill that I recommend is basic coding. A good start point would be learning how to use python to code. There are plenty of free resources for this. 

Next, if you do not have any previous linear algebra experience as well as calculus, you want to really make sure you can understand matrices. This will be useful later on when you delve into learn machine learning.

You want to know how basic statistics works, as according to [this blog](https://data-storyteller.medium.com/how-to-pick-a-masters-program-for-a-career-in-data-science-def0263107ec) the above courses will give you a foundational understanding of data science concepts later on. 

If you want to self learn these subjects, [this road map](https://roadmap.sh/ai-data-scientist) contains a list of resources with the necessary prerequisites as well as related roadmaps if you are interested. A lot of the options presented here are low/no cost.

Also do note that if you plan on applying to a masters degree program, you will likely need a undergraduate degree completed and a combination of these courses to be admitted. This is something that you need to consider as an additional cost and time commitment as well. 


# Skills Required

Once you have a good understanding about some of the prerequisite topics that are required, you may be wondering how are they really applicable? Well, a lot of the additional skills that you need to pick up to become a data scientist would assume you have basic knowledge of these skills already. Let's delve into what additional skills may be required. 

## Data Structures and Algorithms

Classic data structures and algorithms. It is highly important to learn because it can be applied to your future job because learning data structures and algorithm could be the difference between your code taking one minute to run versus it taking thirty minutes to run according to this [blog](https://www.geeksforgeeks.org/why-data-structures-and-algorithms-are-important-to-learn/). 

## ML

Learning about different types of machine learning models, as well as the concepts behind these models is essential in landing a data scientist job. Websites like Kaggle often have practice data sets to work on as well as machine learning competitions. A solid understanding in these topics can also open up the door for machine learning engineering positions. 

## More Advanced Statistics

Probability and statistics is an essential part of a data scientists toolbox.

## Data Visualization in Python

Since you already have experience in using power BI or Tableau, it is worth learning a new data visualization library for python. It is also a good idea to pick up more specialized skills in terms of data visualization such as knowing when to use specific types of visualizations and how to effectively communicate information using visualizations. Some of the common libraries in python include Altair, Seaborn and Plotly. The one you start to practice on does not really matter to be honest because a lot of the syntax for different libraries can be easily learnt and picked up on. Once you are in the job searching process it may be a good idea to look at job postings and see their specific requirements and to cater your learning towards those. 

## Where to Pick Up Data Science Skills

The amount of new skills that you may need to pick up may seem overwhelming right now! With a lot of discipline and hard work, it is not too difficult to learn a lot of these skills. I will break it up into three different ways that you can pick up these required skills as well as go through the pros and cons for each one.

### Master's Program

A masters in data science degree program may be one of the best ways to pick up a lot of skills needed to transition into the industry. There are a wide variety of universities/colleges which offer masters in data science degrees and each one has their own sort of program structure. It may seem overwhelming because of the amount of schools there are, but a lot of your decision will likely come down to your own personal preferences, as well as your own personal research. Some key considerations could be tuition fees, and method of course delivery.  

One of the benefits of attending a masters degree program is that it gives you access to alumni as well as classmates to leverage for networking opportunities. It is also nice to attend a masters degree program since a lot of job postings give preference to those with a masters degree in Data Science.
This can be the difference between getting a rejection you landing that role as a data scientist. The will be elaborated on more in depth later on in the blog. A negative about attending a masters degree program may be that the tuition may really high as well as if it's a full-time commitment, that is a loss of income. If your employer is willing to pay for it, it is advised to enroll. Another option is that some schools offer part-time programs which are done almost entirely online. This allows you to continue working at your current job. 

### Bootcamps

A Boot Camp is also a good way to pick up data science skills as these are fast paced and often challenging experiences. Bootcamps allow you to pick up the necessary skills to be job ready in the field that you are interested in. A lot of them are full-time commitments as well, and can be completed in as little as three months. 

Again, a lot of the same issues that a masters degree program would encounter apply here as well. A lot of these programs are expensive and they require a significant time commitment. Another issue that these programs have when compared to a masters degree is that they may not go into a lot of theory and they may be more focussed on the coding aspects. This may be something to consider depending on your own learning style and preferences. 

### Self Learn / On The Job ()
#### Roadmap

A lot of free resources as well as low cost resources exist. DataCamp is a website that has interactive videos as well as interactive coding and the yearly fee is around $249 USD. Kaggle also exists for learning and practicing data science concepts. 

These resources are good for individuals with limited financial backing who would like to explore the option of transitioning into a data scientist role.

#### Pros and Cons

In the current job market, it is a lot more difficult to get hired this way as a lot of postings require a minimum of a masters degree according to [this DataCamp blog](https://www.datacamp.com/blog/how-to-become-a-data-scientist). In terms of networking, it would be a lot more difficult unless you have a solid network, already established at your current position. 

# Summary Table

| Learning Path     | Cost           | Time Commitment   | Networking Potential   |
|-------------------|----------------|-------------------|------------------------|
| **Master’s Program** | High           | 1-2 years on average         | High                   |
| **Bootcamp**         | Medium-High    | 3-6 months on average        | Medium                 |
| **Self-learn**       | Low/Free           | Flexible          | Low                    |

# Final Tips

- It will be a long process, and it can often be discouraging or it may be difficult to stay motivated. If you experience burn out, try to take a break if you can, as well as surround yourself with peers who may be in the same position as you. A lot of social media data science communities are a good place to meet like-minded folks such as [r/datascience](https://www.reddit.com/r/datascience/). 
- A lot of the advice is very general, if you have a specific role or company in mind, it may be better to focus on what you know they would want.
- Data science is a rapidly changing field, a lot of packages or even new tools may come out from the time you start the process to the day that you landed the job. It is more important to have a good foundation in a lot of the basics such as coding, data structures and algorithms and machine learning versus learning how to use the newest package at all times. You can only go so far with using a new data visualization package if you don't even know the basics behind which chart to use for your specific data. 

## Conclusion

It can be a difficult and often daunting transition into a more specialized discipline. Following what was laid out here is a good starting point for learning new data science skills.

# References
https://www.bls.gov/ooh/math/data-scientists.htm
https://data-storyteller.medium.com/how-to-pick-a-masters-program-for-a-career-in-data-science-def0263107ec
[[1]] https://grad.ucalgary.ca/future-students/explore-programs/data-science-and-analytics-mdsa-course
[[2]] https://masterdatascience.ubc.ca/admissions/prerequisites
[[3]] https://www.torontomu.ca/graduate/datascience/admission/requirements/#!accordion-1499957505732-prerequisite-courses
[[4]]https://roadmap.sh/ai-data-scientist
https://www.datacamp.com/blog/how-to-become-a-data-scientist
https://www.datacamp.com/blog/data-analyst-vs-data-scientist-a-comparative-guide
https://www.reddit.com/r/datascience/
